<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpMind.Core\SharpMind.Core.csproj" />
    <ProjectReference Include="..\SharpMind.Data\SharpMind.Data.csproj" />
    <ProjectReference Include="..\SharpMind.Model\SharpMind.Model.csproj" />
    <ProjectReference Include="..\SharpMind.Tokenizer\SharpMind.Tokenizer.csproj" />
  </ItemGroup>

</Project>
