using LLama;
using SandBox;
using SandBox.RunModels;
//await SandBox.RunModels.DiagnosticModelRunner.RunAsync("Hello", ["gemma-3-270m-it-Q8_0"]);
await SharpMind.Samples.Examples.BuilderOptions.RunAsync("Hello", @"C:\Integral2u\source\repos\SharpMind\ExternalAssets", "qwen2-0_5b-instruct-q8_0");
//await SandBox.RunModels.KnownWorkingModels.RunAsync("Hello");
//await SandBox.RunModels.KnownGiberishModels.RunAsync("Hello");
//await SandBox.RunModels.KnownFailingModels.RunAsync("Hello");
Console.In.ReadLine();
return;