using LLama;
using SandBox;
using SandBox.RunModels;
await SandBox.RunModels.DiagnosticModelRunner.RunAsync("Hello", ["DeepSeek-R1-Distill-Qwen-1.5B-Q8_0", "Qwen3-0.6B-Q8_0"]);
//await SharpMind.Samples.Examples.BuilderOptions.RunAsync("Hello", @"C:\Integral2u\source\repos\SharpMind\ExternalAssets", "qwen2-0_5b-instruct-q8_0");
//await SandBox.RunModels.KnownWorkingModels.RunAsync("Hello");
//await SandBox.RunModels.KnownGiberishModels.RunAsync("Hello");
//await SandBox.RunModels.KnownFailingModels.RunAsync("Hello");
Console.In.ReadLine();
return;