<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ApplicationIcon>SharpMind.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Agent.md" />
    <None Remove="System.md" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SharpMind.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Agent.md" />
    <EmbeddedResource Include="System.md" />
  </ItemGroup>

</Project>
