using SharpMind.Samples.Examples;

namespace SharpMind.Samples.Training;

/// <summary>
/// Calls the models generated by the training examples (<c>pseudo.smm</c> from
/// <see cref="SmmPseudoLanguageExample"/> and <c>tinyshakespeare.smm</c> from
/// <see cref="SmmRealTextExample"/>) with a set of prompts. Each model is loaded
/// once, then every prompt runs in a fresh session before the next model loads.
/// The chat formatter for each model is resolved automatically from the chat
/// template stored in its .SMM file.
/// </summary>
public static class TrainedLanguageExamples
{
    private const string ModelDir = @"c:\temp";
    private const string ModelPseudo = SmmPseudoLanguageExample.Name;
    private const string ModelTinyShakespeare = SmmRealTextExample.Name;
    private static readonly string[] PromptsPseudo =
    [
        "cat"
    ];
    private static readonly string[] PromptsTinyShakespeare =
    [
        "What happens at the end of the play?",
        "Wherefore art thou Romeo",
        "To be, or not to be",
    ];

    public static async Task RunAsync()
    {
        await Console.Out.WriteLineAsync("== Trained language examples ==");
        await Console.Out.WriteLineAsync();

        var models = new List<(string Name, string[] Prompts)>();

        if (!File.Exists(Path.Combine(ModelDir, $"{ModelPseudo}.smm")))
        {
            await Console.Out.WriteLineAsync($"{ModelPseudo}.smm not found.\nDo you want to generate it now (fast) Y or N?");
            var run = await Console.In.ReadLineAsync() ?? string.Empty;
            if (run.Equals("Y", StringComparison.InvariantCultureIgnoreCase))
            {
                await SmmPseudoLanguageExample.RunAsync();
                models.Add((ModelPseudo, PromptsPseudo));
            }
        }
        else
        {
            models.Add((ModelPseudo, PromptsPseudo));
        }

        if (!File.Exists(Path.Combine(ModelDir, $"{ModelTinyShakespeare}.smm")))
        {
            await Console.Out.WriteLineAsync($"{ModelTinyShakespeare}.smm not found.\nDo you want to generate it now (slow) Y or N?");
            var run = await Console.In.ReadLineAsync() ?? string.Empty;
            if (run.Equals("Y", StringComparison.InvariantCultureIgnoreCase))
            {
                await SmmRealTextExample.RunAsync();
                models.Add((ModelTinyShakespeare, PromptsTinyShakespeare));
            }
        }
        else
        {
            models.Add((ModelTinyShakespeare, PromptsTinyShakespeare));
        }
        foreach (var model in models)
        {
            await Console.Out.WriteLineAsync();
            // Multi-prompt overload: load this model once, run all its prompts
            // in fresh sessions, then move on to the next model. formatter: null
            // resolves each model's formatter from its stored chat template.
            await ModelListRunner.RunAsync(model.Prompts, ModelDir, [model.Name], formatter: null);
        }
    }
}