<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharpMind.Model\SharpMind.Model.csproj" />
    <ProjectReference Include="..\..\SharpMind.Inference\SharpMind.Inference.csproj" />
  </ItemGroup>

</Project>