<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>Model loading, architecture, and inference execution for GGUF-based LLMs.</Description>
    <PackageTags>LLM; C#; Machine Learning; Model; GGUF</PackageTags>
    <ApplicationIcon>SharpMind.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="SharpMind.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JigSawDotNet" Version="1.1.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpMind.Core\SharpMind.Core.csproj" />
    <ProjectReference Include="..\SharpMind.Tokenization\SharpMind.Tokenization.csproj" />
  </ItemGroup>

</Project>
