<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>SharpMind.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="SharpMind.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JigSawDotNet" Version="1.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpMind.Core\SharpMind.Core.csproj" />
    <ProjectReference Include="..\SharpMind.Tokenization\SharpMind.Tokenization.csproj" />
  </ItemGroup>

</Project>
