<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>SharpMind.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="SharpMind.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="JigSawDotNet" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpMind.Core\SharpMind.Core.csproj" />
    <ProjectReference Include="..\SharpMind\SharpMind.csproj" />
  </ItemGroup>

</Project>
