<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>SharpMind.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Reference\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SharpMind.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpMind.Core\SharpMind.Core.csproj" />
    <ProjectReference Include="..\SharpMind.Data\SharpMind.Data.csproj" />
    <ProjectReference Include="..\SharpMind.GPU\SharpMind.GPU.csproj" />
    <ProjectReference Include="..\SharpMind.Model\SharpMind.Model.csproj" />
    <ProjectReference Include="..\SharpMind.Samples\SharpMind.Samples.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GPU\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ModelFormat\" />
  </ItemGroup>

</Project>
