<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Description>Zero-dependency tensor primitives and math ops for SharpMind.</Description>
		<PackageTags>LLM; C#; Machine Learning; Tensor</PackageTags>
		<Optimize>true</Optimize>
		<ApplicationIcon>SharpMind.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="SharpMind.ico" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="JigSawDotNet" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SharpMind.Tests" />
  </ItemGroup>



</Project>